# Generated by Django 4.0.3 on 2022-08-23 23:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('monolith_rest', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentsmodel',
            name='commenter_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='comments_model', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='reviewmodel',
            name='reviewer_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='review_model', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='UserModel',
        ),
    ]
