# Generated by Django 4.0.3 on 2022-08-31 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monolith_rest', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movieinformationmodel',
            name='imdb_score',
            field=models.FloatField(null=True),
        ),
    ]
