# Generated by Django 4.0.3 on 2022-08-31 23:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('monolith_rest', '0002_alter_movieinformationmodel_imdb_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movieinformationmodel',
            name='imdb_score',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='movieinformationmodel',
            name='list_of_reviews',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='list_of_reviews', to='monolith_rest.reviewmodel'),
        ),
        migrations.AlterField(
            model_name='movieinformationmodel',
            name='movie_poster',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='movieinformationmodel',
            name='source_author',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='movieinformationmodel',
            name='source_cover',
            field=models.URLField(blank=True, null=True),
        ),
    ]
