# Generated by Django 4.0.3 on 2022-08-25 00:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('monolith_rest', '0003_alter_commentsmodel_commenter_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movieinformationmodel',
            name='list_of_reviews',
        ),
    ]
