# Generated by Django 4.0.3 on 2022-09-01 22:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('monolith_rest', '0003_alter_movieinformationmodel_imdb_score_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movieinformationmodel',
            name='list_of_reviews',
        ),
        migrations.RemoveField(
            model_name='reviewmodel',
            name='movie_name',
        ),
        migrations.AddField(
            model_name='reviewmodel',
            name='movie_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='review_model', to='monolith_rest.movieinformationmodel'),
            preserve_default=False,
        ),
    ]
