# Generated by Django 4.0.3 on 2022-08-25 00:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('monolith_rest', '0004_remove_movieinformationmodel_list_of_reviews'),
    ]

    operations = [
        migrations.AddField(
            model_name='movieinformationmodel',
            name='list_of_reviews',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='list_of_reviews', to='monolith_rest.reviewmodel'),
        ),
    ]
