# Generated by Django 4.0.3 on 2022-09-08 21:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('monolith_rest', '0006_alter_reviewmodel_reviewer_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviewmodel',
            name='movie_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review_model', to='monolith_rest.movieinformationmodel'),
        ),
    ]
