# Generated by Django 4.0.3 on 2022-09-09 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monolith_rest', '0007_alter_reviewmodel_movie_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviewmodel',
            name='admin_rating',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='reviewmodel',
            name='rubric_rating',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
