# Generated by Django 4.0.3 on 2022-09-13 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monolith_rest', '0008_alter_reviewmodel_admin_rating_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movieinformationmodel',
            name='source_cover',
        ),
        migrations.RemoveField(
            model_name='movieinformationmodel',
            name='source_type',
        ),
        migrations.RemoveField(
            model_name='usermodel',
            name='user',
        ),
        migrations.AddField(
            model_name='usermodel',
            name='profile_bio',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='usermodel',
            name='profile_picture',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='movieinformationmodel',
            name='movie_director',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
