# Generated by Django 4.0.3 on 2022-09-13 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monolith_rest', '0010_movieinformationmodel_add_on_rating_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermodel',
            name='user',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
