# Generated by Django 4.0.3 on 2022-09-13 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monolith_rest', '0012_remove_usermodel_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movieinformationmodel',
            name='movie_name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
