# Generated by Django 4.0.3 on 2022-09-15 18:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('monolith_rest', '0013_alter_movieinformationmodel_movie_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CommentsModel',
        ),
    ]
